### ISSUE TITLE
can't compile the provided code

### ISSUE THREAD

**Issue by eea17b** [FSU-ComputerGraphics/CAP4730-Spring19#1]
the provided code can't be compiled 
it gave me this error message
fatal error: 'Eigen/Core' file not found
#include <Eigen/Core>

**Comment by gaoxifeng** [comment]
Hi, which operating system are you using? Did you use the cmake to compile the code?

**Comment by eea17b** [comment]
got it, I did the cmake now and generate the project
but after running the project nothing came out ... is that normal?

**Comment by eea17b** [comment]
I found them, thank you
