### ISSUE TITLE
Compiling Assignment 2 on Windows 10 - Undefined Reference flags

### ISSUE THREAD

**Issue by dra17d** [FSU-ComputerGraphics/CAP4730-Spring19#3]
I have spent the better part of the day attempting to get Assignment 2 to compile. I was able to get cmake to run and create the makefile. However I'm running into undefined references while compiling and have not been able to find a solution online.

Specifically:

`libglew.a(glew.c.obj):glew.c:(.text+0x404): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x436): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x468): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x49a): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x4dc): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x50e): more undefined references to wglGetProcAddress@4' follow
libglew.a(glew.c.obj):glew.c:(.text+0x2629f): undefined reference to wglGetCurrentDC@0'
libglew.a(glew.c.obj):glew.c:(.text+0x262ff): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x26313): undefined reference to wglGetProcAddress@4'
libglew.a(glew.c.obj):glew.c:(.text+0x2634d): undefined reference to wglGetCurrentDC@0'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\Assignment2_bin.dir\build.make:103: recipe for target 'Assignment2_bin.exe' failed
mingw32-make[2]: *** [Assignment2_bin.exe] Error 1
CMakeFiles\Makefile2:72: recipe for target 'CMakeFiles/Assignment2_bin.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/Assignment2_bin.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2`

I am using "mingw32-make" on a command line in the directory where the Makefile is located.

**Comment by gaoxifeng** [comment]
it seems that glew is not found. Are you sure the path to glew is properly set?

**Comment by dra17d** [comment]
Installed Visual Studio 2017 and the project was able to compile and run without issues.
